site_name: Ham's Over IP Wiki
site_url: https://hamsoverip.github.io/wiki
repo_url: https://github.com/hamsoverip/wiki
theme:
  name: 'material'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      primary: 'amber'
      accent: 'orange'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Embrace the dark side
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'deep orange'
      accent: 'amber'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

nav:
  - Welcome!: index.md

  - Main Website (https://hamsoverip.com): https://hamsoverip.com

  - Policies:
    - Terms of Service: General/coming-soon.md
    - User Agreement: General/coming-soon.md
  
  - General User Guides:
    - Joining our Discord Server: General/user_guides/discord.md
    - Finding Help: General/user_guides/support.md
    - Getting Started: General/user_guides/getting-started.md

  - Configuration Guides:
    - Endpoints:
      - Hard Phones:
        - Cisco:
          - Cisco 504G: General/coming-soon.md
          - Cisco 525g: General/coming-soon.md
      - Soft Phones: 
        - Groundwire: General/coming-soon.md
      - PBX Trunks:
        - FreePBX: 
          - Configure FreePBX Trunk: General/coming-soon.md
          - Configure "Auto DND" on FreePBX: General/coming-soon.md
    - Other:
      - Configure an RF Link: endpoints/other/rf-links.md
      - Configure Audio Services: General/coming-soon.md
  
  - Wiki:
    - Contributing: 
      - Overview of the Wiki: wiki/overview.md
      - How to Contribute: wiki/contributing.md

extra:
  social:
    - icon: 'fontawesome/brands/discord'
      link: 'https://discord.gg/6VgdWw3vM4'

